### ISSUE TITLE
several configs are ignored

### ISSUE THREAD

**Issue by kouhate** [ledisdb/redis-failover#3]
Hi @siddontang ,

Following options in failover.toml seem to be ignored in spite of using -config=/path/to/failover.toml.

<pre>
broker=""
[raft]
data_dir=""
log_dir=""
</pre>

Additionally, sometimes I get these error and failover is not performed when I use -broker=raft.

<pre>
[2015/02/16 11:57:13] app.go:260 [Info] 127.0.0.1:11000 is not leader, skip
</pre>

This may happen when the cluster gives no response.
Setting invalid node to it causes same thing.

When I set invalid zk node using -broker=zk, proper messages are shown.

<pre>
2015/02/16 13:15:33 Failed to connect to 127.0.0.1:2180: dial tcp 127.0.0.1:2180: connection refused
</pre>

It would be better to check cluster's health and raize error in the same way as zk.

**Comment by siddontang** [comment]
3Q now I am in journey, see later.

**Comment by siddontang** [comment]
Hi @kouhate, for raft, if the node is not the leader, it may be follower or candidate, and would be leader later. If you use raft, only leader can do the failover, so other nodes will skip to check.

For zk, because we depend on another service, so if the zookeeper is not ok, the redis-failover will not ok too, so we have to raise an error.

**Comment by kouhate** [comment]
Hi @siddontang, maybe I found the reason why failover was failed.

Now 2 ledis-server is running.

<pre>
// master
192.168.0.1:6380> role
1) "master"
2) (integer) 9
3) 1) 1) "192.168.0.2"
      2) "6380"
      3) "9"
// slave
192.168.0.2:6380> role
1) "slave"
2) "192.168.0.1"
3) (integer) 6380
4) "connected"
5) (integer) 9
</pre>

Then restart master.

<pre>
// master
192.168.0.1:6380> role
1) "master"
2) (integer) 9
3) 1) 1) "192.168.0.2"
      2) "6380"
      3) "0"
</pre>

<code>3) 1) 3) number</code> is changed 9 to 0.

SLAVEOF command for slave return nothing.

<pre>
// slave
192.168.0.2:6380> slaveof no one
..... maybe crashed....
</pre>

This may prevent failover operation.

**Comment by siddontang** [comment]
Thank you, I will see later.

**Comment by siddontang** [comment]
Hi @kouhate, I try to fix it in ledisdb develop branch, you can check again.

**Comment by kouhate** [comment]
Hi @siddontang, fixed perfectly!
Thanks.
